doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        # 'DoctrineMigrations': '%kernel.project_dir%/Shared/Infrastructure/Database/Write/Migrations'
        'App\Shared\Infrastructure\Database\Write\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Database/Write/Migrations'
    enable_profiler: false
