version: "3.4"

services:
  nginx:
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2-fpm
      - postgres-15.3
  php8.2-fpm:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    volumes:
      - ./:/var/www/project
  postgres-15.3:
    build:
      context: ./docker
      dockerfile: ./postgres/Dockerfile
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"


